version: "3"
services:
  api:
    # in production, you don't use build, but you use your image from the dockerhub
    image: thedockerbear/fastapi-course-api
    depends_on:
      - postgres
    ports:
      - "80:8000"
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    #    env_file:
#      - ./.env
    environment:
      - DRIVER_NAME=${DRIVER_NAME}  # referencing env variables reading from the prod system env var
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      -
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:



